### ISSUE TITLE
[ci] verify helm chart can be generated

### ISSUE THREAD

**Issue by stuartnelson3** [elastic/apm-k8s-attacher#14]
As part of the CI pipeline, verify that there are no issues generating the helm chart yaml files from the [template](https://github.com/elastic/apm-mutating-webhook/blob/main/apm-agent-auto-attach/templates/webhook.yaml).

Something along the lines of

```
helm upgrade -i webhook apm-agent-auto-attach/ --dry-run --debug --namespace=elastic-apm --create-namespace
```

**Comment by simitt** [comment]
I haven't followed all the changes in the repo, but this seems outdated. cc @trentm

**Comment by jackshirazi** [comment]
We do the helm install from main/branch as part of the integration test run against all changes
