### ISSUE TITLE
investigate writing e2e tests

### ISSUE THREAD

**Issue by stuartnelson3** [elastic/apm-k8s-attacher#23]
https://github.com/elastic/e2e-testing/tree/main/e2e/_suites/kubernetes-autodiscover

**Comment by kuisathaverat** [comment]
For unit test and integrations test of the helm chart these frameworks are nice

* https://github.com/quintush/helm-unittest
* https://github.com/helm/chart-testing
* https://kubetest.readthedocs.io/en/latest/index.html

We are working on a Helm chart for the Opbeans to use it on the oblt clusters. That helm chart and the webhook helm chart can join in a parent Helm chart to make integration tests, and e2e tests. The process would be something like this:
* Deploy the Stack on ESS
* Deploy the mutating webhook Helm Chart
* Deploy an Opbean configured to use the mutating webhook
* Run some validations
* Run some e2e test
* Report test results.

**Comment by jackshirazi** [comment]
We have ended-to-end tests working, and a framework that let's any additional language agent to be integration test
