### ISSUE TITLE
Add helm commands to artifacthub.io for the webhook

### ISSUE THREAD

**Issue by simitt** [elastic/apm-k8s-attacher#53]
Similar to how the artifacthub.io instructs you to run the helm commands (https://artifacthub.io/packages/helm/elastic/eck-operator), we shoould add the same to our documentation: https://artifacthub.io/packages/helm/elastic/eck-operator?modal=install

**Comment by simitt** [comment]
@trentm @estolfo IMO this is not critical for GA, but a nice to have.

**Comment by trentm** [comment]
I may be confused. Is this not satisfied by https://www.elastic.co/guide/en/apm/attacher/current/apm-webhook-install-helm.html ?

**Comment by simitt** [comment]
you're right, I had overlooked that the instructions are available already.
