### ISSUE TITLE
Add minimal test for .NET

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-k8s-attacher#73]
Currently the test coverage for .NET is very little: https://github.com/elastic/apm-mutating-webhook/tree/main/test

We should add a minimal test, following the Node.js test. 

What should be covered (feel free to extend or change if it makes sense):
- Real container is started with a minimal sample app
- A real request runs against the sample app
- The test makes sure the agent was injected properly and captured the call
- Tests fails if the agent did not capture the call

Same for Java: https://github.com/elastic/apm-mutating-webhook/issues/72

**Comment by Mpdreamz** [comment]
Implemented as part of #73
